-- Seed: AI Resources (53 curated entries)
-- Run after schema.sql migration

-- University section (7)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('university', 'CS229 · Machine Learning', 'Stanford / Andrew Ng', 'The gold-standard academic ML course covering supervised, unsupervised, and reinforcement learning with rigorous math.', 'material', 'Advanced', '["machine-learning","supervised","unsupervised","stanford"]', '["12 weeks","Lecture notes & problem sets"]', 'https://cs229.stanford.edu/', 0),
('university', 'CS50''s Introduction to AI with Python', 'Harvard', 'Harvard''s hands-on introduction to AI concepts using Python — graph search, neural nets, NLP, and more.', 'material', 'Beginner', '["python","search","neural-networks","nlp","harvard"]', '["7 weeks","Free certificate available"]', 'https://pll.harvard.edu/course/cs50s-introduction-artificial-intelligence-python', 0),
('university', 'MIT OpenCourseWare · AI & ML', 'MIT', 'Free lecture notes, exams, and assignments from MIT''s AI and machine learning courses.', 'material', 'Intermediate', '["mit","machine-learning","deep-learning","free"]', '["Self-paced","Multiple courses"]', 'https://ocw.mit.edu/search/?q=artificial+intelligence', 0),
('university', 'fast.ai · Practical Deep Learning for Coders', 'fast.ai', 'Top-down, code-first deep learning course — start building models on day one. 6M+ video views, endorsed by Peter Norvig.', 'material', 'Beginner', '["deep-learning","pytorch","practical","fast.ai"]', '["9 lessons","~90 min each"]', 'https://course.fast.ai/', 0),
('university', 'Neural Networks and Deep Learning', 'Michael Nielsen', 'Free online book offering deep intuition for neural networks and backprop with interactive visualizations.', 'material', 'Intermediate', '["neural-networks","backprop","book","free"]', '["Free book","Interactive"]', 'http://neuralnetworksanddeeplearning.com/', 0),
('university', 'Deep Learning', 'Goodfellow, Bengio & Courville', 'The definitive deep learning textbook covering fundamentals through advanced topics like GANs and sequence models.', 'material', 'Advanced', '["deep-learning","textbook","gans","rnn"]', '["Free online","MIT Press"]', 'https://www.deeplearningbook.org/', 0),
('university', 'Khan Academy · Math for AI', 'Khan Academy', 'Free courses on linear algebra, calculus, probability and statistics — the mathematical foundations for ML.', 'material', 'Beginner', '["math","linear-algebra","calculus","probability","free"]', '["Self-paced","Free"]', 'https://www.khanacademy.org/math', 0);

-- Industry section (14)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('industry', 'DeepLearning.AI Short Courses', 'DeepLearning.AI', 'Short, practical courses on LLMs, RAG, agents, and more — built with industry partners like OpenAI, Hugging Face, and AWS.', 'material', 'Beginner', '["llm","rag","agents","practical","andrew-ng"]', '["1–4 hours each","Free audit"]', 'https://www.deeplearning.ai/short-courses/', 0),
('industry', 'Hugging Face Course', 'Hugging Face', 'Hands-on NLP and transformers course using the Hugging Face ecosystem — from tokenizers to fine-tuning.', 'material', 'Intermediate', '["nlp","transformers","hugging-face","fine-tuning"]', '["Free","Notebooks included"]', 'https://huggingface.co/learn', 0),
('industry', 'Anthropic Prompt Engineering Guide', 'Anthropic', 'Official guide to writing effective prompts for Claude — covers chain-of-thought, few-shot, and advanced techniques.', 'material', 'Intermediate', '["prompting","claude","anthropic","chain-of-thought"]', '["Official docs","Free"]', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview', 0),
('industry', 'Google ML Crash Course', 'Google', 'Google''s free intro to machine learning with TensorFlow — covers regression, classification, neural networks.', 'material', 'Beginner', '["google","tensorflow","machine-learning","free"]', '["~15 hours","Free"]', 'https://developers.google.com/machine-learning/crash-course/', 0),
('industry', 'LangChain Academy', 'LangChain', 'Free courses on building LLM applications with LangChain and LangGraph, including agentic workflows.', 'material', 'Intermediate', '["langchain","langgraph","agents","llm"]', '["Free","Official"]', 'https://academy.langchain.com/', 1),
('industry', 'Full Stack Deep Learning', 'Full Stack Deep Learning', 'Practical course covering the full ML product lifecycle — from experimentation to production deployment.', 'material', 'Advanced', '["mlops","deployment","production","full-stack"]', '["Free","2022 edition"]', 'https://fullstackdeeplearning.com/course/2022/', 0),
('industry', 'OpenAI Agents SDK Quickstart', 'OpenAI', 'Official quickstart for building multi-agent systems with the OpenAI Agents SDK — tools, handoffs, and guardrails.', 'material', 'Intermediate', '["openai","agents","sdk","multi-agent"]', '["Official docs","Python"]', 'https://openai.github.io/openai-agents-python/quickstart/', 1),
('industry', 'Coursera AI & ML Courses', 'Coursera', 'Hundreds of AI and ML courses from top universities and companies — many free to audit.', 'material', 'Beginner', '["coursera","machine-learning","free-audit","certificates"]', '["Free audit","Certificates paid"]', 'https://www.coursera.org/search?query=machine+learning', 0),
('industry', 'Microsoft Learn · AI', 'Microsoft', 'Free learning paths for Azure AI, Copilot, and machine learning fundamentals from Microsoft.', 'material', 'Beginner', '["microsoft","azure","ai","free"]', '["Free","Badges & certs"]', 'https://learn.microsoft.com/en-us/training/browse/?products=ai-services', 0),
('industry', 'Papers With Code', 'Papers With Code', 'Browse ML research papers with linked code implementations — track state-of-the-art across every benchmark.', 'material', 'Advanced', '["research","papers","benchmarks","sota"]', '["Free","Updated daily"]', 'https://paperswithcode.com/', 0),
('industry', 'OpenAI Cookbook', 'OpenAI', 'Practical examples and guides for building with the OpenAI API — RAG, embeddings, function calling, and more.', 'material', 'Intermediate', '["openai","api","rag","embeddings","cookbook"]', '["Free","Code examples"]', 'https://cookbook.openai.com/', 0),
('industry', 'Learn Prompting', 'Learn Prompting', 'Open-source guide to prompt engineering — beginner through advanced techniques with examples.', 'material', 'Beginner', '["prompting","prompt-engineering","free","open-source"]', '["Free","Community maintained"]', 'https://learnprompting.org/', 0),
('industry', 'ArXiv · AI & ML', 'ArXiv', 'The primary preprint server for AI and ML research — access the latest papers before journal publication.', 'material', 'Advanced', '["research","papers","preprints","academic"]', '["Free","Daily updates"]', 'https://arxiv.org/list/cs.AI/recent', 0),
('industry', 'Awesome Machine Learning', 'GitHub · josephmisiti', 'Curated GitHub list of ML frameworks, libraries, and software organized by language and topic.', 'material', 'Beginner', '["curated","libraries","frameworks","github"]', '["Community curated","GitHub"]', 'https://github.com/josephmisiti/awesome-machine-learning', 0);

-- Videos section (15)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('videos', 'Andrej Karpathy YouTube', 'Andrej Karpathy', 'Deep, first-principles explanations of neural networks, backprop, and language models from a legendary AI practitioner.', 'video', 'Intermediate', '["neural-networks","llm","backprop","deep-learning"]', '["YouTube","Free"]', 'https://www.youtube.com/@AndrejKarpathy', 0),
('videos', 'Stanford CS25 Transformers United', 'Stanford Online', 'Stanford seminar series featuring leading researchers on transformers, LLMs, and foundation models.', 'video', 'Advanced', '["transformers","llm","stanford","research"]', '["YouTube","Academic"]', 'https://www.youtube.com/playlist?list=PLoROMvodv4rNiJRchCzutFw5ItR_Z27CM', 0),
('videos', 'freeCodeCamp AI Playlist', 'freeCodeCamp', 'Comprehensive free AI and ML tutorials — Python, TensorFlow, PyTorch, and full project walkthroughs.', 'video', 'Beginner', '["free","python","tensorflow","pytorch","tutorials"]', '["YouTube","Free"]', 'https://www.youtube.com/@freecodecamp', 0),
('videos', 'ML Zoomcamp', 'DataTalks.Club', 'Free 4-month ML engineering bootcamp — regression to deployment, with homework and a capstone project.', 'video', 'Beginner', '["bootcamp","ml-engineering","deployment","free"]', '["YouTube","4 months","Free"]', 'https://www.youtube.com/watch?v=MqI8vt3-cag&list=PL3MmuxUbc_hL5QBBEyKUXKuTNx-3cTpKs', 0),
('videos', 'ML YouTube Courses (dair-ai)', 'dair-ai · GitHub', 'Curated index of the best free ML/AI YouTube course playlists — covers NLP, CV, RL, and more.', 'material', 'Beginner', '["curated","youtube","free","index","dair-ai"]', '["GitHub","17k+ stars"]', 'https://github.com/dair-ai/ML-YouTube-Courses', 0),
('videos', '3Blue1Brown · Neural Networks', '3Blue1Brown', 'Beautiful visual explanations of neural networks, gradient descent, and transformers — the best intro for visual learners.', 'video', 'Beginner', '["visual","neural-networks","gradient-descent","transformers"]', '["YouTube","Free"]', 'https://www.youtube.com/@3blue1brown', 0),
('videos', 'Yannic Kilcher', 'Yannic Kilcher', 'In-depth paper walkthroughs and AI news commentary — popular with ML researchers and advanced practitioners.', 'video', 'Advanced', '["research","papers","gpt","transformers"]', '["YouTube","Free"]', 'https://www.youtube.com/@YannicKilcher', 0),
('videos', 'Two Minute Papers', 'Two Minute Papers', 'Accessible 5–10 minute summaries of cutting-edge AI research papers — great for staying current.', 'video', 'Intermediate', '["research","papers","summaries","news"]', '["YouTube","Free","Short videos"]', 'https://www.youtube.com/@TwoMinutePapers', 0),
('videos', 'Lex Fridman Podcast', 'Lex Fridman', 'Long-form interviews with leading AI researchers (Hinton, LeCun, Karpathy, Musk) — great for context and inspiration.', 'video', 'Intermediate', '["interviews","researchers","context","inspiration"]', '["YouTube","Podcast","Free"]', 'https://www.youtube.com/@lexfridman', 0),
('videos', 'Sentdex', 'Sentdex', 'Practical Python ML and AI tutorials — from scikit-learn basics to building neural networks from scratch.', 'video', 'Beginner', '["python","scikit-learn","practical","tutorials"]', '["YouTube","Free"]', 'https://www.youtube.com/@sentdex', 0),
('videos', 'Stanford CS231n · Computer Vision', 'Stanford University', 'Stanford''s definitive computer vision course — CNNs, object detection, segmentation, and generative models.', 'video', 'Advanced', '["computer-vision","cnn","stanford","object-detection"]', '["YouTube","Academic"]', 'https://www.youtube.com/playlist?list=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv', 0),
('videos', 'MIT 6.S191 · Introduction to Deep Learning', 'MIT', 'MIT''s annual deep learning bootcamp — CNNs, RNNs, GANs, and reinforcement learning in one week.', 'video', 'Intermediate', '["mit","deep-learning","cnn","rnn","gan"]', '["YouTube","Annual","Free"]', 'https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI', 0),
('videos', 'Neural Networks: Zero to Hero', 'Andrej Karpathy', 'Karpathy''s structured course building neural networks from scratch — from micrograd to nanoGPT.', 'video', 'Intermediate', '["neural-networks","from-scratch","gpt","backprop"]', '["YouTube","Team Pick","Free"]', 'https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ', 1),
('videos', 'AI Explained', 'AI Explained', 'Clear, accessible explanations of GPT-4, Claude, Gemini, and AI trends — great for non-technical audiences.', 'video', 'Beginner', '["gpt-4","gemini","claude","explainers","non-technical"]', '["YouTube","Free"]', 'https://www.youtube.com/@aiexplained-official', 0),
('videos', 'DeepMind · Reinforcement Learning', 'UCL & DeepMind', 'UCL/DeepMind''s comprehensive lecture series on reinforcement learning — Q-learning, policy gradients, and more.', 'video', 'Advanced', '["reinforcement-learning","deepmind","ucl","q-learning"]', '["YouTube","Academic","Free"]', 'https://www.youtube.com/playlist?list=PLqYmG7hTraZDVH599EItlEWsUOsJbAodm', 0);

-- Tooling section (17)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('tooling', 'ChatGPT', 'OpenAI', 'OpenAI''s conversational AI — the most widely used LLM for writing, coding, analysis, and learning.', 'tool', 'Beginner', '["chatgpt","openai","llm","chat"]', '["Web + mobile","Free tier"]', 'https://chatgpt.com/', 0),
('tooling', 'Perplexity', 'Perplexity AI', 'AI-powered search engine that cites sources — great for research, fact-checking, and technical questions.', 'tool', 'Beginner', '["search","research","citations","llm"]', '["Web","Free tier"]', 'https://www.perplexity.ai/', 0),
('tooling', 'n8n', 'n8n', 'Open-source workflow automation with 400+ integrations — connect AI models to any data source or service.', 'tool', 'Intermediate', '["automation","workflow","open-source","integrations"]', '["Self-host or cloud","Free community edition"]', 'https://n8n.io/', 0),
('tooling', 'NotebookLM', 'Google', 'Google''s AI research assistant — upload documents and have conversations grounded in your own sources.', 'tool', 'Beginner', '["research","documents","google","grounded-ai"]', '["Free","Web"]', 'https://notebooklm.google/', 1),
('tooling', 'CrewAI', 'CrewAI', 'Framework for orchestrating autonomous multi-agent AI crews — define roles, tools, and workflows in Python.', 'tool', 'Intermediate', '["agents","multi-agent","python","orchestration"]', '["Open source","Python"]', 'https://docs.crewai.com/en/quickstart', 1),
('tooling', 'Agent Skills', 'agentskills.io', 'Platform for discovering, sharing, and deploying reusable AI agent skills and tools.', 'tool', 'Intermediate', '["agents","skills","platform","reusable"]', '["Web","Community"]', 'https://agentskills.io/home', 0),
('tooling', 'Kaggle', 'Kaggle · Google', 'The world''s largest data science community — competitions, free GPU notebooks, datasets, and courses.', 'tool', 'Beginner', '["competitions","datasets","notebooks","free-gpu"]', '["Free","Competitions"]', 'https://www.kaggle.com/', 0),
('tooling', 'LlamaIndex', 'LlamaIndex', 'Data framework for building LLM applications — indexing, retrieval, and agentic pipelines over your data.', 'tool', 'Intermediate', '["rag","retrieval","llm","indexing","python"]', '["Open source","Python"]', 'https://www.llamaindex.ai/', 0),
('tooling', 'Weights & Biases', 'Weights & Biases', 'MLOps platform for experiment tracking, model versioning, and dataset visualization.', 'tool', 'Intermediate', '["mlops","experiment-tracking","logging","model-registry"]', '["Free for individuals","Hosted"]', 'https://wandb.ai/', 0),
('tooling', 'Google AI Studio', 'Google', 'Browser-based IDE for experimenting with Gemini models — test prompts, tune parameters, and get API keys.', 'tool', 'Beginner', '["google","gemini","prompt-testing","api"]', '["Free","Web"]', 'https://aistudio.google.com/', 0),
('tooling', 'Replit AI', 'Replit', 'AI-powered coding environment in the browser — generate, edit, and run code with AI assistance.', 'tool', 'Beginner', '["coding","browser","ai-coding","ide"]', '["Free tier","Web"]', 'https://replit.com/', 0),
('tooling', 'Gamma', 'Gamma', 'AI-powered presentation and document builder — turn text into polished slides in seconds.', 'tool', 'Beginner', '["presentations","slides","productivity","generative"]', '["Free tier","Web"]', 'https://gamma.app/', 0),
('tooling', 'ElevenLabs', 'ElevenLabs', 'AI voice synthesis platform — generate realistic speech, clone voices, and build audio experiences.', 'tool', 'Beginner', '["voice","tts","audio","speech-synthesis"]', '["Free tier","API"]', 'https://elevenlabs.io/', 0),
('tooling', 'Leonardo.ai', 'Leonardo.ai', 'AI image generation platform with fine-tuned models — create art, product shots, and game assets.', 'tool', 'Beginner', '["image-generation","art","stable-diffusion","creative"]', '["Free tier","Web"]', 'https://leonardo.ai/', 0),
('tooling', 'Suno AI', 'Suno', 'AI music generation — create full songs with lyrics and instrumentation from a text prompt.', 'tool', 'Beginner', '["music","audio","generative","creative"]', '["Free tier","Web"]', 'https://suno.com/', 0),
('tooling', 'Ideogram', 'Ideogram', 'AI image generation with exceptional text rendering — create logos, posters, and graphics with accurate text.', 'tool', 'Beginner', '["image-generation","text-in-images","logos","creative"]', '["Free tier","Web"]', 'https://ideogram.ai/', 0),
('tooling', 'Taskade', 'Taskade', 'AI-powered productivity workspace — tasks, notes, mind maps, and AI agents in one place.', 'tool', 'Beginner', '["productivity","tasks","ai-agents","collaboration"]', '["Free tier","Web + mobile"]', 'https://www.taskade.com/', 0);
