-- Seed: AI Resources (60 curated entries)
-- Run after schema.sql migration

-- University section (14)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('university', 'CS229 · Machine Learning', 'Stanford / Andrew Ng', 'The gold-standard academic ML course covering supervised, unsupervised, and reinforcement learning with rigorous math.', 'material', 'Advanced', '["machine-learning","supervised","unsupervised","stanford"]', '["12 weeks","Lecture notes & problem sets"]', 'https://cs229.stanford.edu/', 0),
('university', 'CS50''s Introduction to AI with Python', 'Harvard', 'Harvard''s hands-on introduction to AI concepts using Python — graph search, neural nets, NLP, and more.', 'material', 'Beginner', '["python","search","neural-networks","nlp","harvard"]', '["7 weeks","Free certificate available"]', 'https://pll.harvard.edu/course/cs50s-introduction-artificial-intelligence-python', 0),
('university', 'MIT OpenCourseWare · AI & ML', 'MIT', 'Free lecture notes, exams, and assignments from MIT''s AI and machine learning courses.', 'material', 'Intermediate', '["mit","machine-learning","deep-learning","free"]', '["Self-paced","Multiple courses"]', 'https://ocw.mit.edu/search/?q=artificial+intelligence', 0),
('university', 'fast.ai · Practical Deep Learning for Coders', 'fast.ai', 'Top-down, code-first deep learning course — start building models on day one. 6M+ video views, endorsed by Peter Norvig.', 'material', 'Beginner', '["deep-learning","pytorch","practical","fast.ai"]', '["9 lessons","~90 min each"]', 'https://course.fast.ai/', 0),
('university', 'Neural Networks and Deep Learning', 'Michael Nielsen', 'Free online book offering deep intuition for neural networks and backprop with interactive visualizations.', 'material', 'Intermediate', '["neural-networks","backprop","book","free"]', '["Free book","Interactive"]', 'http://neuralnetworksanddeeplearning.com/', 0),
('university', 'Deep Learning', 'Goodfellow, Bengio & Courville', 'The definitive deep learning textbook covering fundamentals through advanced topics like GANs and sequence models.', 'material', 'Advanced', '["deep-learning","textbook","gans","rnn"]', '["Free online","MIT Press"]', 'https://www.deeplearningbook.org/', 0),
('university', 'Khan Academy · Math for AI', 'Khan Academy', 'Free courses on linear algebra, calculus, probability and statistics — the mathematical foundations for ML.', 'material', 'Beginner', '["math","linear-algebra","calculus","probability","free"]', '["Self-paced","Free"]', 'https://www.khanacademy.org/math', 0),
('university', 'CS221 · Artificial Intelligence: Principles and Techniques', 'Stanford University', 'Stanford''s broad intro to AI — ML, search, MDPs, game playing, constraint satisfaction, graphical models, and logic. Lecture videos on YouTube.', 'material', 'Intermediate', '["stanford","ai","search","mdp","logic","free"]', '["Lecture Notes + Video","Intermediate"]', 'https://stanford-cs221.github.io/', 0),
('university', 'CS224N · Natural Language Processing with Deep Learning', 'Stanford University', 'Deep dive into NLP and LLMs — word vectors, transformers, BERT, GPT, RLHF, agents, and RAG. Full 2024 lecture playlist freely available on YouTube.', 'material', 'Advanced', '["stanford","nlp","llm","transformers","rlhf","free"]', '["Video + Slides","Advanced"]', 'https://www.youtube.com/playlist?list=PLoROMvodv4rOaMFbaqxPDoLWjDaRAdP9D', 0),
('university', 'CS230 · Deep Learning', 'Stanford University · Andrew Ng', 'Andrew Ng''s deep learning course at Stanford: CNNs, RNNs, optimization, and project work. Free Fall 2018 lecture videos on YouTube.', 'material', 'Intermediate', '["stanford","deep-learning","cnn","rnn","andrew-ng","free"]', '["Video + Coursera","Intermediate"]', 'https://cs230.stanford.edu/', 0),
('university', 'CS234 · Reinforcement Learning', 'Stanford University · Emma Brunskill', 'Stanford''s core RL course — MDPs, Q-learning, policy gradients, RLHF, and deep RL. Lecture videos on YouTube. Textbook is Sutton & Barto (free online).', 'material', 'Advanced', '["stanford","reinforcement-learning","rl","mdp","rlhf","free"]', '["Video + Notes","Advanced"]', 'https://cs234.stanford.edu/', 0),
('university', 'MIT 6.034 · Artificial Intelligence', 'MIT OpenCourseWare · Patrick Winston', 'Classic MIT undergrad AI course with full lecture videos. Covers search, constraint satisfaction, learning, neural nets, and vision — timeless foundations.', 'material', 'Intermediate', '["mit","ai","search","neural-networks","free","ocw"]', '["Full Video Course","Intermediate"]', 'https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/', 0),
('university', 'MIT 6.867 · Machine Learning', 'MIT OpenCourseWare', 'MIT graduate ML course with comprehensive lecture notes and problem sets. Covers regression, classification, SVMs, HMMs, and Bayesian networks.', 'material', 'Advanced', '["mit","machine-learning","svm","hmm","bayesian","free","ocw"]', '["Lecture Notes","Graduate"]', 'https://ocw.mit.edu/courses/6-867-machine-learning-fall-2006/', 0),
('university', 'MIT 6.S191 · Introduction to Deep Learning', 'MIT · Alexander Amini', 'MIT''s intensive intro to deep learning with TensorFlow labs. Covers CNNs, RNNs, GANs, and reinforcement learning. Lectures free at introtodeeplearning.com.', 'material', 'Intermediate', '["mit","deep-learning","tensorflow","cnn","rnn","gan","free"]', '["Video + Labs","Intermediate"]', 'http://introtodeeplearning.com/', 0);

-- Industry section (14)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('industry', 'DeepLearning.AI Short Courses', 'DeepLearning.AI', 'Short, practical courses on LLMs, RAG, agents, and more — built with industry partners like OpenAI, Hugging Face, and AWS.', 'material', 'Beginner', '["llm","rag","agents","practical","andrew-ng"]', '["1–4 hours each","Free audit"]', 'https://www.deeplearning.ai/short-courses/', 0),
('industry', 'Machine Learning Specialization', 'Stanford / DeepLearning.AI', '3-course specialization by Andrew Ng covering supervised learning, neural networks, unsupervised learning, recommender systems, and reinforcement learning. Updated version of his legendary course, now in Python with TensorFlow. Rated 4.9/5 by 38,500+ learners. Requires Coursera subscription (~$49/month); financial aid available.', 'material', 'Beginner', '["stanford","andrew-ng","coursera","machine-learning","paid","certificate"]', '["~95 hours total","Paid (~$49/month)","Financial aid available"]', 'https://www.coursera.org/specializations/machine-learning-introduction', 0),
('industry', 'Hugging Face Course', 'Hugging Face', 'Hands-on NLP and transformers course using the Hugging Face ecosystem — from tokenizers to fine-tuning.', 'material', 'Intermediate', '["nlp","transformers","hugging-face","fine-tuning"]', '["Free","Notebooks included"]', 'https://huggingface.co/learn', 0),
('industry', 'Anthropic Prompt Engineering Guide', 'Anthropic', 'Official guide to writing effective prompts for Claude — covers chain-of-thought, few-shot, and advanced techniques.', 'material', 'Intermediate', '["prompting","claude","anthropic","chain-of-thought"]', '["Official docs","Free"]', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview', 0),
('industry', 'Google ML Crash Course', 'Google', 'Google''s free intro to machine learning with TensorFlow — covers regression, classification, neural networks.', 'material', 'Beginner', '["google","tensorflow","machine-learning","free"]', '["~15 hours","Free"]', 'https://developers.google.com/machine-learning/crash-course/', 0),
('industry', 'LangChain Academy', 'LangChain', 'Free courses on building LLM applications with LangChain and LangGraph, including agentic workflows.', 'material', 'Intermediate', '["langchain","langgraph","agents","llm"]', '["Free","Official"]', 'https://academy.langchain.com/', 1),
('industry', 'Full Stack Deep Learning', 'Full Stack Deep Learning', 'Practical course covering the full ML product lifecycle — from experimentation to production deployment.', 'material', 'Advanced', '["mlops","deployment","production","full-stack"]', '["Free","2022 edition"]', 'https://fullstackdeeplearning.com/course/2022/', 0),
('industry', 'OpenAI Agents SDK Quickstart', 'OpenAI', 'Official quickstart for building multi-agent systems with the OpenAI Agents SDK — tools, handoffs, and guardrails.', 'material', 'Intermediate', '["openai","agents","sdk","multi-agent"]', '["Official docs","Python"]', 'https://openai.github.io/openai-agents-python/quickstart/', 1),
('industry', 'Coursera AI & ML Courses', 'Coursera', 'Hundreds of AI and ML courses from top universities and companies — many free to audit.', 'material', 'Beginner', '["coursera","machine-learning","free-audit","certificates"]', '["Free audit","Certificates paid"]', 'https://www.coursera.org/search?query=machine+learning', 0),
('industry', 'Microsoft Learn · AI', 'Microsoft', 'Free learning paths for Azure AI, Copilot, and machine learning fundamentals from Microsoft.', 'material', 'Beginner', '["microsoft","azure","ai","free"]', '["Free","Badges & certs"]', 'https://learn.microsoft.com/en-us/training/browse/?products=ai-services', 0),
('industry', 'Papers With Code', 'Papers With Code', 'Browse ML research papers with linked code implementations — track state-of-the-art across every benchmark.', 'material', 'Advanced', '["research","papers","benchmarks","sota"]', '["Free","Updated daily"]', 'https://paperswithcode.com/', 0),
('industry', 'OpenAI Cookbook', 'OpenAI', 'Practical examples and guides for building with the OpenAI API — RAG, embeddings, function calling, and more.', 'material', 'Intermediate', '["openai","api","rag","embeddings","cookbook"]', '["Free","Code examples"]', 'https://cookbook.openai.com/', 0),
('industry', 'Learn Prompting', 'Learn Prompting', 'Open-source guide to prompt engineering — beginner through advanced techniques with examples.', 'material', 'Beginner', '["prompting","prompt-engineering","free","open-source"]', '["Free","Community maintained"]', 'https://learnprompting.org/', 0),
('industry', 'ArXiv · AI & ML', 'ArXiv', 'The primary preprint server for AI and ML research — access the latest papers before journal publication.', 'material', 'Advanced', '["research","papers","preprints","academic"]', '["Free","Daily updates"]', 'https://arxiv.org/list/cs.AI/recent', 0),
('industry', 'Awesome Machine Learning', 'GitHub · josephmisiti', 'Curated GitHub list of ML frameworks, libraries, and software organized by language and topic.', 'material', 'Beginner', '["curated","libraries","frameworks","github"]', '["Community curated","GitHub"]', 'https://github.com/josephmisiti/awesome-machine-learning', 0),
('industry', 'How to AI · Ruben Hassid', 'Ruben Hassid · Substack', 'Weekly practical AI workflow guides — exact prompts, screenshots, and step-by-step walkthroughs for Claude, ChatGPT, and AI tools. 528K+ subscribers. Great for non-technical practitioners.', 'material', 'Beginner', '["newsletter","practical","prompting","claude","chatgpt","workflow","free"]', '["Weekly newsletter","Beginner-friendly"]', 'https://rubenhassid.substack.com/', 1);

-- Videos section (15)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('videos', 'Andrej Karpathy YouTube', 'Andrej Karpathy', 'Deep, first-principles explanations of neural networks, backprop, and language models from a legendary AI practitioner.', 'video', 'Intermediate', '["neural-networks","llm","backprop","deep-learning"]', '["YouTube","Free"]', 'https://www.youtube.com/@AndrejKarpathy', 0),
('videos', 'Stanford CS25 Transformers United', 'Stanford Online', 'Stanford seminar series featuring leading researchers on transformers, LLMs, and foundation models.', 'video', 'Advanced', '["transformers","llm","stanford","research"]', '["YouTube","Academic"]', 'https://www.youtube.com/playlist?list=PLoROMvodv4rNiJRchCzutFw5ItR_Z27CM', 0),
('videos', 'freeCodeCamp AI Playlist', 'freeCodeCamp', 'Comprehensive free AI and ML tutorials — Python, TensorFlow, PyTorch, and full project walkthroughs.', 'video', 'Beginner', '["free","python","tensorflow","pytorch","tutorials"]', '["YouTube","Free"]', 'https://www.youtube.com/@freecodecamp', 0),
('videos', 'ML Zoomcamp', 'DataTalks.Club', 'Free 4-month ML engineering bootcamp — regression to deployment, with homework and a capstone project.', 'video', 'Beginner', '["bootcamp","ml-engineering","deployment","free"]', '["YouTube","4 months","Free"]', 'https://www.youtube.com/watch?v=MqI8vt3-cag&list=PL3MmuxUbc_hL5QBBEyKUXKuTNx-3cTpKs', 0),
('videos', 'ML YouTube Courses (dair-ai)', 'dair-ai · GitHub', 'Curated index of the best free ML/AI YouTube course playlists — covers NLP, CV, RL, and more.', 'material', 'Beginner', '["curated","youtube","free","index","dair-ai"]', '["GitHub","17k+ stars"]', 'https://github.com/dair-ai/ML-YouTube-Courses', 0),
('videos', '3Blue1Brown · Neural Networks', '3Blue1Brown', 'Beautiful visual explanations of neural networks, gradient descent, and transformers — the best intro for visual learners.', 'video', 'Beginner', '["visual","neural-networks","gradient-descent","transformers"]', '["YouTube","Free"]', 'https://www.youtube.com/@3blue1brown', 0),
('videos', 'Yannic Kilcher', 'Yannic Kilcher', 'In-depth paper walkthroughs and AI news commentary — popular with ML researchers and advanced practitioners.', 'video', 'Advanced', '["research","papers","gpt","transformers"]', '["YouTube","Free"]', 'https://www.youtube.com/@YannicKilcher', 0),
('videos', 'Two Minute Papers', 'Two Minute Papers', 'Accessible 5–10 minute summaries of cutting-edge AI research papers — great for staying current.', 'video', 'Intermediate', '["research","papers","summaries","news"]', '["YouTube","Free","Short videos"]', 'https://www.youtube.com/@TwoMinutePapers', 0),
('videos', 'Lex Fridman Podcast', 'Lex Fridman', 'Long-form interviews with leading AI researchers (Hinton, LeCun, Karpathy, Musk) — great for context and inspiration.', 'video', 'Intermediate', '["interviews","researchers","context","inspiration"]', '["YouTube","Podcast","Free"]', 'https://www.youtube.com/@lexfridman', 0),
('videos', 'Sentdex', 'Sentdex', 'Practical Python ML and AI tutorials — from scikit-learn basics to building neural networks from scratch.', 'video', 'Beginner', '["python","scikit-learn","practical","tutorials"]', '["YouTube","Free"]', 'https://www.youtube.com/@sentdex', 0),
('videos', 'Stanford CS231n · Computer Vision', 'Stanford University', 'Stanford''s definitive computer vision course — CNNs, object detection, segmentation, and generative models.', 'video', 'Advanced', '["computer-vision","cnn","stanford","object-detection"]', '["YouTube","Academic"]', 'https://www.youtube.com/playlist?list=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv', 0),
('videos', 'MIT 6.S191 · Introduction to Deep Learning', 'MIT', 'MIT''s annual deep learning bootcamp — CNNs, RNNs, GANs, and reinforcement learning in one week.', 'video', 'Intermediate', '["mit","deep-learning","cnn","rnn","gan"]', '["YouTube","Annual","Free"]', 'https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI', 0),
('videos', 'Neural Networks: Zero to Hero', 'Andrej Karpathy', 'Karpathy''s structured course building neural networks from scratch — from micrograd to nanoGPT.', 'video', 'Intermediate', '["neural-networks","from-scratch","gpt","backprop"]', '["YouTube","Team Pick","Free"]', 'https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ', 1),
('videos', 'AI Explained', 'AI Explained', 'Clear, accessible explanations of GPT-4, Claude, Gemini, and AI trends — great for non-technical audiences.', 'video', 'Beginner', '["gpt-4","gemini","claude","explainers","non-technical"]', '["YouTube","Free"]', 'https://www.youtube.com/@aiexplained-official', 0),
('videos', 'DeepMind · Reinforcement Learning', 'UCL & DeepMind', 'UCL/DeepMind''s comprehensive lecture series on reinforcement learning — Q-learning, policy gradients, and more.', 'video', 'Advanced', '["reinforcement-learning","deepmind","ucl","q-learning"]', '["YouTube","Academic","Free"]', 'https://www.youtube.com/playlist?list=PLqYmG7hTraZDVH599EItlEWsUOsJbAodm', 0);

-- Tooling section (17)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('tooling', 'ChatGPT', 'OpenAI', 'OpenAI''s conversational AI — the most widely used LLM for writing, coding, analysis, and learning.', 'tool', 'Beginner', '["chatgpt","openai","llm","chat"]', '["Web + mobile","Free tier"]', 'https://chatgpt.com/', 0),
('tooling', 'Perplexity', 'Perplexity AI', 'AI-powered search engine that cites sources — great for research, fact-checking, and technical questions.', 'tool', 'Beginner', '["search","research","citations","llm"]', '["Web","Free tier"]', 'https://www.perplexity.ai/', 0),
('tooling', 'n8n', 'n8n', 'Open-source workflow automation with 400+ integrations — connect AI models to any data source or service.', 'tool', 'Intermediate', '["automation","workflow","open-source","integrations"]', '["Self-host or cloud","Free community edition"]', 'https://n8n.io/', 0),
('tooling', 'NotebookLM', 'Google', 'Google''s AI research assistant — upload documents and have conversations grounded in your own sources.', 'tool', 'Beginner', '["research","documents","google","grounded-ai"]', '["Free","Web"]', 'https://notebooklm.google/', 1),
('tooling', 'CrewAI', 'CrewAI', 'Framework for orchestrating autonomous multi-agent AI crews — define roles, tools, and workflows in Python.', 'tool', 'Intermediate', '["agents","multi-agent","python","orchestration"]', '["Open source","Python"]', 'https://docs.crewai.com/en/quickstart', 1),
('tooling', 'Agent Skills', 'agentskills.io', 'Platform for discovering, sharing, and deploying reusable AI agent skills and tools.', 'tool', 'Intermediate', '["agents","skills","platform","reusable"]', '["Web","Community"]', 'https://agentskills.io/home', 0),
('tooling', 'Kaggle', 'Kaggle · Google', 'The world''s largest data science community — competitions, free GPU notebooks, datasets, and courses.', 'tool', 'Beginner', '["competitions","datasets","notebooks","free-gpu"]', '["Free","Competitions"]', 'https://www.kaggle.com/', 0),
('tooling', 'LlamaIndex', 'LlamaIndex', 'Data framework for building LLM applications — indexing, retrieval, and agentic pipelines over your data.', 'tool', 'Intermediate', '["rag","retrieval","llm","indexing","python"]', '["Open source","Python"]', 'https://www.llamaindex.ai/', 0),
('tooling', 'Weights & Biases', 'Weights & Biases', 'MLOps platform for experiment tracking, model versioning, and dataset visualization.', 'tool', 'Intermediate', '["mlops","experiment-tracking","logging","model-registry"]', '["Free for individuals","Hosted"]', 'https://wandb.ai/', 0),
('tooling', 'Google AI Studio', 'Google', 'Browser-based IDE for experimenting with Gemini models — test prompts, tune parameters, and get API keys.', 'tool', 'Beginner', '["google","gemini","prompt-testing","api"]', '["Free","Web"]', 'https://aistudio.google.com/', 0),
('tooling', 'Replit AI', 'Replit', 'AI-powered coding environment in the browser — generate, edit, and run code with AI assistance.', 'tool', 'Beginner', '["coding","browser","ai-coding","ide"]', '["Free tier","Web"]', 'https://replit.com/', 0),
('tooling', 'Gamma', 'Gamma', 'AI-powered presentation and document builder — turn text into polished slides in seconds.', 'tool', 'Beginner', '["presentations","slides","productivity","generative"]', '["Free tier","Web"]', 'https://gamma.app/', 0),
('tooling', 'ElevenLabs', 'ElevenLabs', 'AI voice synthesis platform — generate realistic speech, clone voices, and build audio experiences.', 'tool', 'Beginner', '["voice","tts","audio","speech-synthesis"]', '["Free tier","API"]', 'https://elevenlabs.io/', 0),
('tooling', 'Leonardo.ai', 'Leonardo.ai', 'AI image generation platform with fine-tuned models — create art, product shots, and game assets.', 'tool', 'Beginner', '["image-generation","art","stable-diffusion","creative"]', '["Free tier","Web"]', 'https://leonardo.ai/', 0),
('tooling', 'Suno AI', 'Suno', 'AI music generation — create full songs with lyrics and instrumentation from a text prompt.', 'tool', 'Beginner', '["music","audio","generative","creative"]', '["Free tier","Web"]', 'https://suno.com/', 0),
('tooling', 'Ideogram', 'Ideogram', 'AI image generation with exceptional text rendering — create logos, posters, and graphics with accurate text.', 'tool', 'Beginner', '["image-generation","text-in-images","logos","creative"]', '["Free tier","Web"]', 'https://ideogram.ai/', 0),
('tooling', 'Taskade', 'Taskade', 'AI-powered productivity workspace — tasks, notes, mind maps, and AI agents in one place.', 'tool', 'Beginner', '["productivity","tasks","ai-agents","collaboration"]', '["Free tier","Web + mobile"]', 'https://www.taskade.com/', 0);

-- Anthropic Skilljar Courses (11 curated)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('industry', 'Claude 101', 'Anthropic', 'Official intro course to Claude — how to use it effectively for everyday work tasks, core features, and best practices. Free with Skilljar account.', 'material', 'Beginner', '["anthropic","claude","free","beginner","skilljar"]', '["Free","~1 hour","Skilljar"]', 'https://anthropic.skilljar.com/claude-101', 0),
('industry', 'Claude Code 101', 'Anthropic', 'Learn to use Claude Code in your daily development workflow — agentic coding, terminal integration, and best practices.', 'material', 'Beginner', '["anthropic","claude","coding","free","developers","skilljar"]', '["Free","Skilljar"]', 'https://anthropic.skilljar.com/claude-code-101', 0),
('industry', 'AI Fluency: Framework & Foundations', 'Anthropic', 'Learn to collaborate with AI effectively, ethically, and safely — mindset, prompting fundamentals, and responsible use. Great for any role.', 'material', 'Beginner', '["anthropic","ai-literacy","ethics","free","skilljar"]', '["Free","Skilljar"]', 'https://anthropic.skilljar.com/ai-fluency-framework-foundations', 0),
('industry', 'AI Capabilities and Limitations', 'Anthropic', 'Introductory course on how AI works, what it can and cannot do, and how to reason about its outputs responsibly.', 'material', 'Beginner', '["anthropic","ai-literacy","free","skilljar"]', '["Free","Skilljar"]', 'https://anthropic.skilljar.com/ai-capabilities-and-limitations', 0),
('industry', 'Building with the Claude API', 'Anthropic', 'Full-spectrum course for developers building with the Claude API — prompting, tool use, context windows, and production patterns.', 'material', 'Intermediate', '["anthropic","claude","api","developers","free","skilljar"]', '["Free","Skilljar","Developer"]', 'https://anthropic.skilljar.com/claude-with-the-anthropic-api', 0),
('industry', 'Introduction to Model Context Protocol', 'Anthropic', 'Build MCP servers and clients in Python — tools, resources, prompts, and the MCP architecture. The protocol that connects AI models to data and tools.', 'material', 'Intermediate', '["anthropic","mcp","python","developers","agentic","free","skilljar"]', '["Free","Skilljar","Python"]', 'https://anthropic.skilljar.com/introduction-to-model-context-protocol', 0),
('industry', 'Model Context Protocol: Advanced Topics', 'Anthropic', 'Advanced MCP patterns — sampling, notifications, file system integration, and custom transports. For developers building production MCP integrations.', 'material', 'Advanced', '["anthropic","mcp","python","agentic","advanced","free","skilljar"]', '["Free","Skilljar","Advanced"]', 'https://anthropic.skilljar.com/model-context-protocol-advanced-topics', 0),
('industry', 'Introduction to Agent Skills', 'Anthropic', 'Learn to build, configure, and share Skills in Claude Code — reusable agent capabilities for development workflows.', 'material', 'Intermediate', '["anthropic","agents","claude","coding","free","skilljar"]', '["Free","Skilljar"]', 'https://anthropic.skilljar.com/introduction-to-agent-skills', 0),
('industry', 'Introduction to Subagents', 'Anthropic', 'Learn to use and create sub-agents in Claude Code — delegate tasks, build multi-agent pipelines, and orchestrate agentic workflows.', 'material', 'Intermediate', '["anthropic","agents","multi-agent","agentic","free","skilljar"]', '["Free","Skilljar"]', 'https://anthropic.skilljar.com/introduction-to-subagents', 0),
('industry', 'Claude with Amazon Bedrock', 'Anthropic', 'Complete course for developers and architects working with Claude through AWS Bedrock — provisioning, API calls, and production patterns.', 'material', 'Intermediate', '["anthropic","claude","aws","bedrock","cloud","free","skilljar"]', '["Free","Skilljar","AWS"]', 'https://anthropic.skilljar.com/claude-in-amazon-bedrock', 0),
('industry', 'Claude with Google Cloud Vertex AI', 'Anthropic', 'Working with Claude through Google Cloud Vertex AI — deployment, API integration, and enterprise use cases on GCP.', 'material', 'Intermediate', '["anthropic","claude","google-cloud","vertex-ai","cloud","free","skilljar"]', '["Free","Skilljar","GCP"]', 'https://anthropic.skilljar.com/claude-with-google-vertex', 0);

-- MIT Open Learning courses (8 from LinkedIn post — new additions)
INSERT INTO resources (section, title, source, description, type, level, tags, meta, url, is_team_pick) VALUES
('university', 'MIT 6.036 · Introduction to Machine Learning', 'MIT Open Learning Library', 'MIT''s hands-on ML course covering formulation of learning problems, supervised learning, reinforcement learning, and applications to images and temporal sequences. Fully free with no registration required.', 'material', 'Intermediate', '["mit","machine-learning","supervised","reinforcement-learning","free"]', '["13 weeks","~12 hrs/week"]', 'https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.036+1T2019/about', 0),
('university', 'MIT 6.S087 · Foundation Models and Generative AI', 'MIT OpenCourseWare', 'Non-technical MIT course on how modern AI tools work — ChatGPT, DALL-E, AlphaFold, and self-supervised learning. Free lecture videos on OCW.', 'material', 'Beginner', '["mit","generative-ai","foundation-models","chatgpt","dall-e","free","ocw"]', '["Video","IAP 2024"]', 'https://ocw.mit.edu/courses/6-s087-foundation-models-and-generative-ai-january-iap-2024/', 0),
('university', 'MITx · Understanding the World Through Data', 'MITx Online', 'Learn to use data and ML to make sense of the real world — regression, classification, and data distributions with Python. Free to audit; certificate $49.', 'material', 'Beginner', '["mit","data-science","python","machine-learning","free-audit"]', '["Free audit","Certificate $49"]', 'https://mitxonline.mit.edu/courses/course-v1:MITxT+6.UWTDx/', 0),
('university', 'MIT RES.6-013 · AI 101', 'MIT OpenCourseWare', 'Beginner-friendly MIT intro to AI concepts — participants train their own algorithm and learn how AI thinks and solves problems. Fully free on OCW.', 'material', 'Beginner', '["mit","ai","beginner","free","ocw"]', '["Free","OCW"]', 'https://ocw.mit.edu/courses/res-6-013-ai-101-fall-2021/', 0),
('university', 'MITx 6.86x · Machine Learning with Python', 'MITx / edX', 'MIT''s comprehensive ML course — linear models, SVMs, neural networks, and reinforcement learning. Free to audit on edX; part of the MITx Statistics and Data Science MicroMasters.', 'material', 'Advanced', '["mit","machine-learning","python","svm","neural-networks","free-audit"]', '["Free audit","Certificate $300"]', 'https://www.edx.org/learn/machine-learning/massachusetts-institute-of-technology-machine-learning-with-python-from-linear-models-to-deep-learning', 0),
('university', 'MIT MAS.S60 · How to AI (Almost) Anything', 'MIT OpenCourseWare · Paul Liang', 'Applying modern deep learning and foundation models to novel real-world modalities — vision, audio, sensors, medical data, music, art, and multimodal AI. Spring 2025.', 'material', 'Intermediate', '["mit","multimodal-ai","foundation-models","free","ocw"]', '["Lecture Notes","Spring 2025"]', 'https://ocw.mit.edu/courses/mas-s60-how-to-ai-almost-anything-spring-2025/', 0),
('university', 'MIT 6.S062 · Generative AI in K–12 Education', 'MIT OpenCourseWare', 'Explores how generative AI tools affect K–12 curricula and teaching — project-based, covering ethics, implications, and hands-on experimentation. Fully free on OCW.', 'material', 'Beginner', '["mit","generative-ai","education","ethics","free","ocw"]', '["Free","OCW 2023"]', 'https://ocw.mit.edu/courses/6-s062-generative-artificial-intelligence-in-k12-education-fall-2023/', 0),
('university', 'MIT 6.006 · Introduction to Algorithms', 'MIT OpenCourseWare', 'MIT''s foundational algorithms course — data structures, sorting, graph algorithms, dynamic programming, and performance analysis. The logic behind fast and smart AI systems.', 'material', 'Intermediate', '["mit","algorithms","data-structures","computer-science","free","ocw"]', '["Video + Problem Sets","Spring 2020"]', 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', 0);
